# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregos_app', '0002_listaempregos_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoEmpregos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areadeatuacao', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='listaempregos',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
