# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-22 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregos_app', '0004_auto_20180422_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaempregos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
