# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-22 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregos_app', '0005_auto_20180422_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaempregos',
            name='salario',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
