# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregos_app', '0006_listaempregos_salario'),
    ]

    operations = [
        migrations.CreateModel(
            name='listaEmpresas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
    ]
