# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empregos_app', '0008_listaempresas_nomeemprego'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listaempregos',
            name='autor',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listaempresas',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
