# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empregos_app', '0009_auto_20180422_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaempregos',
            name='contato',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listaempregos',
            name='titulo',
            field=models.TextField(max_length=100),
        ),
    ]
